stages:
    - build
    - release
cache:
  paths:
    - node_modules

build:
  image: node:8
  stage: build
  script:
    - yarn install
    - ng-packagr
  artifacts:
    paths:
      - dist
      - node_modules

publish:
  image: node:8
  stage: release
  only:
    - master
  script:
    - npx semantic-release